const canvas = document.querySelector('#game');
const ctx = canvas.getContext('2d');
const ui = {
  gold: document.querySelector('#gold'), lives: document.querySelector('#lives'), wave: document.querySelector('#wave'), difficulty: document.querySelector('#difficulty'),
  toast: document.querySelector('#toast'), waveButton: document.querySelector('#waveButton'), autoWaveButton: document.querySelector('#autoWaveButton'), rollButton: document.querySelector('#rollButton'), rouletteTower: document.querySelector('#rouletteTower') || document.querySelector('#diceFace'),
  inventory: document.querySelector('#inventory'), towerCategories: document.querySelector('#towerCategories'), upgradePanel: document.querySelector('#upgradePanel'), resetViewButton: document.querySelector('#resetViewButton'), mapButton: document.querySelector('#mapButton'), previousMapButton: document.querySelector('#previousMapButton'), saveButton: document.querySelector('#saveButton'), indexButton: document.querySelector('#indexButton'), indexPanel: document.querySelector('#indexPanel'), statsButton: document.querySelector('#statsButton'), statsPanel: document.querySelector('#statsPanel'), drawCost: document.querySelector('#drawCost') || document.querySelector('#rollButton small'), rouletteLevel: document.querySelector('#rouletteLevel'), modal: document.querySelector('#modal'), modalTitle: document.querySelector('#modalTitle'), modalText: document.querySelector('#modalText'), baseUpgradeChoices: document.querySelector('#baseUpgradeChoices'), startButton: document.querySelector('#startButton')
};

const W = canvas.width, H = canvas.height;
const SAVE_KEY = 'fortune-bastion-save-v1';
const STATS_KEY = 'fortune-bastion-stats-v1';
const PROGRESS_KEY = 'fortune-bastion-permanent-progress-v1';
const BASE_DRAW_COST = 100;
const DEATH_DRAW_COST_INCREASE = 50;
const BASE_INSTALL_SLOTS = 5;
const PORTAL_PROGRESS = 62;
const maps = [
  {stage:1, name:'VERDANT COAST', theme:{grass:'#2c8754', grassAlt:'#338e58', water:'#4ba1b7', shore:'#d9c889'}, path:[{x:-40,y:125},{x:225,y:125},{x:225,y:425},{x:560,y:425},{x:560,y:238},{x:870,y:238},{x:870,y:510},{x:1140,y:510}], pads:[{x:150,y:230},{x:300,y:215},{x:390,y:335},{x:470,y:520},{x:665,y:330},{x:755,y:145},{x:760,y:430},{x:955,y:365},{x:985,y:565}]},
  {stage:2, name:'EMBER CANYON', theme:{grass:'#806241', grassAlt:'#916f47', water:'#a75e3e', shore:'#e0ae62'}, path:[{x:-40,y:540},{x:160,y:540},{x:160,y:610},{x:330,y:610},{x:330,y:170},{x:530,y:170},{x:530,y:500},{x:790,y:500},{x:790,y:110},{x:1140,y:110}], pads:[{x:78,y:395},{x:245,y:450},{x:260,y:565},{x:425,y:300},{x:440,y:580},{x:635,y:315},{x:670,y:605},{x:665,y:410},{x:900,y:300},{x:925,y:585},{x:1040,y:260}]},
  {stage:3, name:'FROSTWIND PASS', theme:{grass:'#497f77', grassAlt:'#5d938b', water:'#65a6c2', shore:'#d8e6dd'}, path:[{x:-40,y:245},{x:170,y:245},{x:170,y:100},{x:400,y:100},{x:400,y:570},{x:640,y:570},{x:640,y:145},{x:850,y:145},{x:850,y:550},{x:1030,y:550},{x:1030,y:350},{x:1140,y:350}], pads:[{x:78,y:405},{x:285,y:310},{x:285,y:55},{x:300,y:450},{x:505,y:315},{x:520,y:630},{x:540,y:430},{x:745,y:300},{x:750,y:620},{x:950,y:320},{x:945,y:620},{x:1080,y:470}]}
];
let currentMapIndex=0;
let path=maps[0].path.map(point=>({...point}));
let pads=maps[0].pads.map(point=>({...point}));
const enemyTypes = [
  {name:'Field Crawler', hp:1, speed:1, damage:1, r:12, body:'#b5474e', top:'#f36d59'},
  {name:'Swift Runner', hp:.62, speed:1.48, damage:1, r:9, body:'#ce7541', top:'#ffad65'},
  {name:'Iron Brute', hp:1.75, speed:.72, damage:3, r:16, body:'#65727f', top:'#aebfca'},
  {name:'Moss Swarm', hp:.48, speed:1.26, damage:1, r:8, body:'#547a42', top:'#91c564'},
  {name:'Crystal Bug', hp:.86, speed:1.08, damage:2, r:11, body:'#615798', top:'#aa93ed'},
  {name:'Ash Hound', hp:1.18, speed:.94, damage:2, r:13, body:'#7c493f', top:'#da765c'},
  {name:'Tide Skipper', hp:.7, speed:1.66, damage:1, r:9, body:'#2d6e8c', top:'#71d8ee'},
  {name:'Bramble Boar', hp:1.52, speed:.84, damage:3, r:15, body:'#52673b', top:'#a6cf67'},
  {name:'Dune Scarab', hp:1.08, speed:1.16, damage:2, r:12, body:'#8d6839', top:'#f0c96b'},
  {name:'Gloom Moth', hp:.58, speed:1.38, damage:2, r:8, body:'#3e3b68', top:'#b4a6ff'},
  {name:'Frost Ram', hp:1.95, speed:.68, damage:4, r:17, body:'#4b7280', top:'#b9f2fa'},
  {name:'Cinder Imp', hp:.82, speed:1.31, damage:2, r:10, body:'#8b3f35', top:'#ff9367'}
];
const eliteTypes = [
  {name:'Iron Colossus', hp:2.45, speed:.62, damage:5, r:22, body:'#6d617b', top:'#e49dff'},
  {name:'Void Warden', hp:1.9, speed:.82, damage:4, r:20, body:'#3c496c', top:'#75baff'},
  {name:'Ember Juggernaut', hp:2.15, speed:.74, damage:5, r:21, body:'#813e3d', top:'#ff9d65'},
  {name:'Glacier Sentinel', hp:2.7, speed:.56, damage:6, r:23, body:'#457687', top:'#b7fbff'},
  {name:'Thorn Matriarch', hp:2.18, speed:.7, damage:5, r:21, body:'#556f42', top:'#ccf27c'},
  {name:'Storm Reaver', hp:1.72, speed:.98, damage:5, r:19, body:'#45486d', top:'#98c8ff'}
];
const wave30Boss = {name:'Ancient Bastion', hp:1, speed:.48, damage:12, r:34, body:'#5e3946', top:'#ffd66e'};
const grades = [
  {id:'common', label:'COMMON', multiplier:.72, chance:50, color:'#b8c8c5'},
  {id:'uncommon', label:'UNCOMMON', multiplier:.9, chance:26, color:'#85eb87'},
  {id:'rare', label:'RARE', multiplier:1.12, chance:14, color:'#78c8ff'},
  {id:'epic', label:'EPIC', multiplier:1.42, chance:7, color:'#db8dff'},
  {id:'legendary', label:'LEGENDARY', multiplier:1.8, chance:3, color:'#ffd360'},
  {id:'mythic', label:'MYTHIC', multiplier:2.2, chance:1.6, color:'#ff83ce'},
  {id:'ancient', label:'ANCIENT', multiplier:2.65, chance:1.1, color:'#ff9b61'},
  {id:'celestial', label:'CELESTIAL', multiplier:3.15, chance:.75, color:'#80f6ff'},
  {id:'divine', label:'DIVINE', multiplier:3.75, chance:.5, color:'#fff3a1'},
  {id:'transcendent', label:'TRANSCENDENT', multiplier:4.45, chance:.3, color:'#ff6f9b'}
];
const archetypes = [
  {id:'spark-coil', name:'Spark Coil', icon:'SPK', kind:'spark', ability:'chain', range:132, fireRate:.38, damage:14},
  {id:'arc-beacon', name:'Arc Beacon', icon:'ARC', kind:'spark', ability:'shock', range:150, fireRate:.48, damage:18},
  {id:'volt-prism', name:'Volt Prism', icon:'VLT', kind:'spark', ability:'prism', range:120, fireRate:.3, damage:12},
  {id:'storm-pylon', name:'Storm Pylon', icon:'STM', kind:'spark', ability:'storm', range:160, fireRate:.58, damage:24},
  {id:'root-cannon', name:'Root Cannon', icon:'CAN', kind:'cannon', ability:'splash', range:172, fireRate:1.08, damage:48},
  {id:'bastion-mortar', name:'Bastion Mortar', icon:'MOR', kind:'cannon', ability:'mortar', range:205, fireRate:1.44, damage:68},
  {id:'ember-howitzer', name:'Ember Howitzer', icon:'EMB', kind:'cannon', ability:'burn', range:148, fireRate:.82, damage:42},
  {id:'thorn-garden', name:'Thorn Garden', icon:'THN', kind:'thorns', ability:'root', range:42, fireRate:.42, damage:10},
  {id:'frost-bramble', name:'Frost Bramble', icon:'FRS', kind:'thorns', ability:'freeze', range:55, fireRate:.58, damage:15},
  {id:'venom-hedge', name:'Venom Hedge', icon:'VNM', kind:'thorns', ability:'poison', range:48, fireRate:.34, damage:9}
];
const types = Object.fromEntries(grades.flatMap(grade => archetypes.map(archetype => {
  const id = `${grade.id}-${archetype.id}`;
  return [id, {...archetype, id, modelId:archetype.id, name:`${grade.label} ${archetype.name}`, grade:grade.id, gradeLabel:grade.label, color:grade.color, range:Math.round(archetype.range * grade.multiplier), fireRate:archetype.fireRate / Math.pow(grade.multiplier, .3), damage:Math.round(archetype.damage * grade.multiplier)}];
})));
const startingInventory = Object.fromEntries(Object.keys(types).map(id => [id, []]));
startingInventory['common-spark-coil'].push(1);
startingInventory['common-root-cannon'].push(1);
startingInventory['common-thorn-garden'].push(1);
function freshInventory() { return Object.fromEntries(Object.entries(startingInventory).map(([id, levels]) => [id, [...levels]])); }
let inventory = freshInventory();
let selected = 'common-spark-coil';
let towerCategory = 'all';
let gold = 320, lives = 20, wave = 0, drawCost = BASE_DRAW_COST, running = false, gameOver = false, last = performance.now(), toastTimer;
const unlockedMaps = [true, false, false];
const mapTowerStates = maps.map(() => []);
let towers = [], enemies = [], shots = [], particles = [], spawnQueue = [], spawnCooldown = 0, selectedTower = null, fusionMode = false, isDrawing = false, drawTimer, drawSpinTimer, autoWave = false, autoWaveTimer;
const baseUpgrades = {luck:0, fortify:0, power:0, roulette:0, slots:0};
const overallStats = {kills:0, normalKills:0, eliteKills:0, bossKills:0, suppliesEarned:0, draws:0, wavesStarted:0, wavesCleared:0, highestWave:0, deaths:0};
const camera = {x:W/2, y:H/2, zoom:1};
const cameraKeys = new Set();

function persistOverallStats() { try { localStorage.setItem(STATS_KEY,JSON.stringify(overallStats)); } catch {} }
function loadOverallStats() { try { const saved=JSON.parse(localStorage.getItem(STATS_KEY)); Object.keys(overallStats).forEach(key=>{if(Number.isFinite(saved?.[key]))overallStats[key]=Math.max(0,Math.floor(saved[key]));}); } catch {} }
function recordStats(changes) { Object.entries(changes).forEach(([key,value])=>{if(key in overallStats)overallStats[key]+=value;}); persistOverallStats(); }
function recordWaveStats() { recordStats({wavesStarted:1}); if(wave>overallStats.highestWave){overallStats.highestWave=wave;persistOverallStats();} }
function persistPermanentProgress() { try { localStorage.setItem(PROGRESS_KEY,JSON.stringify({unlockedMaps:[...unlockedMaps],baseUpgrades:{...baseUpgrades}})); } catch {} }
function loadPermanentProgress() { try { const saved=JSON.parse(localStorage.getItem(PROGRESS_KEY)); if(!saved) return false; if(Array.isArray(saved.unlockedMaps))saved.unlockedMaps.forEach((value,index)=>{if(index<unlockedMaps.length)unlockedMaps[index]=unlockedMaps[index]||!!value;}); Object.keys(baseUpgrades).forEach(id=>{if(Number.isFinite(saved.baseUpgrades?.[id]))baseUpgrades[id]=Math.max(baseUpgrades[id],Math.max(0,Math.min(getUpgradeMax(id),Math.floor(saved.baseUpgrades[id]))));}); return true; } catch { return false; } }
loadOverallStats();

function resetView() { camera.x=W/2; camera.y=H/2; camera.zoom=1; }
function isMapUnlocked(index) { return unlockedMaps[index]; }
function updateMapButton() { const next=(currentMapIndex+1)%maps.length, previous=(currentMapIndex-1+maps.length)%maps.length, nextMap=maps[next], previousMap=maps[previous]; ui.mapButton.textContent=`NEXT: ${isMapUnlocked(next) ? `S${nextMap.stage} ${nextMap.name}` : `S${nextMap.stage} LOCKED`}`; if(ui.previousMapButton) ui.previousMapButton.textContent=`PREV: ${isMapUnlocked(previous) ? `S${previousMap.stage} ${previousMap.name}` : `S${previousMap.stage} LOCKED`}`; }
function updateAutoWaveButton() { ui.autoWaveButton.textContent=`AUTO WAVE: ${autoWave ? 'ON' : 'OFF'}`; ui.autoWaveButton.classList.toggle('on',autoWave); }
function serializeTower(tower) { return {typeId:tower.type.id,level:tower.level,x:tower.x,y:tower.y,padIndex:tower.pad?pads.indexOf(tower.pad):-1,pathTrap:!!tower.pathTrap}; }
function captureCurrentMapLayout() { mapTowerStates[currentMapIndex]=towers.map(serializeTower); }
function restoreTowerLayout(layout) { towers=[]; for(const saved of layout||[]){const type=types[saved.typeId],pad=saved.padIndex>=0?pads[saved.padIndex]:null;if(!type||!Number.isFinite(saved.x)||!Number.isFinite(saved.y)||(pad&&pad.tower))continue;const tower={x:saved.x,y:saved.y,type,level:Math.max(1,Math.min(saved.level||1,getMaxLevel({type}))),cooldown:0,angle:-Math.PI/2,pulse:0,pad,pathTrap:!!saved.pathTrap};if(pad)pad.tower=tower;towers.push(tower);} }
function setMap(index) { if(running) return say('Finish the current wave before changing maps.'); const map=maps[index]; if(!isMapUnlocked(index)) return say(`Stage ${map.stage} is locked. Unlock it from the defeat upgrade screen.`); captureCurrentMapLayout(); selectedTower=null; fusionMode=false; currentMapIndex=index; path=map.path.map(point=>({...point})); pads=map.pads.map(point=>({...point})); pathLength=calculatePathLength(); restoreTowerLayout(mapTowerStates[currentMapIndex]); persistPermanentProgress(); resetView(); updateUI(); say(`Stage ${map.stage}: ${map.name} selected. Permanent upgrades retained.`); }
function serializeEnemy(enemy) { return {typeName:enemy.type.name,progress:enemy.progress,spawnProgress:enemy.spawnProgress,speed:enemy.speed,hp:enemy.hp,maxHp:enemy.maxHp,damage:enemy.damage,reward:enemy.reward,slow:enemy.slow,slowFactor:enemy.slowFactor,poison:enemy.poison,poisonDamage:enemy.poisonDamage,burn:enemy.burn,burnDamage:enemy.burnDamage,statusTick:enemy.statusTick,hit:enemy.hit}; }
function restoreSavedEnemy(saved) { const type=[...enemyTypes,...eliteTypes,wave30Boss].find(entry=>entry.name===saved.typeName); if(!type||!Number.isFinite(saved.progress)||!Number.isFinite(saved.hp)) return null; const boss=type===wave30Boss,elite=eliteTypes.includes(type),progress=Math.max(PORTAL_PROGRESS,saved.progress),spawnProgress=Math.min(progress,Math.max(0,Number.isFinite(saved.spawnProgress)?saved.spawnProgress:PORTAL_PROGRESS)),maxHp=Math.max(1,Math.floor(saved.maxHp||1)),enemy={progress,spawnProgress,speed:Math.max(1,Number(saved.speed)||1),hp:Math.max(1,Math.min(maxHp,Number(saved.hp))),maxHp,damage:Math.max(1,Math.floor(saved.damage||type.damage)),reward:Math.max(0,Math.floor(saved.reward||0)),r:type.r,elite,boss,type,slow:Math.max(0,Number(saved.slow)||0),slowFactor:Math.max(.25,Math.min(1,Number(saved.slowFactor)||1)),poison:Math.max(0,Number(saved.poison)||0),poisonDamage:Math.max(0,Number(saved.poisonDamage)||0),burn:Math.max(0,Number(saved.burn)||0),burnDamage:Math.max(0,Number(saved.burnDamage)||0),statusTick:Math.max(0,Number(saved.statusTick)||0),hit:Math.max(0,Number(saved.hit)||0)}; const pos=pointOnPath(progress); return {...enemy,x:pos.x,y:pos.y,angle:pos.angle}; }
function saveGame() { try { captureCurrentMapLayout(); persistPermanentProgress(); const state={version:1,mapIndex:currentMapIndex,unlockedMaps:[...unlockedMaps],baseUpgrades:{...baseUpgrades},gold,lives,wave,drawCost,running,autoWave,spawnQueue:[...spawnQueue],spawnCooldown,enemies:enemies.map(serializeEnemy),inventory,mapTowerStates:mapTowerStates.map(layout=>layout.map(tower=>({...tower}))),towers:mapTowerStates[currentMapIndex],selected,camera:{...camera}}; localStorage.setItem(SAVE_KEY,JSON.stringify(state)); say(running?'Wave progress saved in this browser.':'Game saved in this browser.'); } catch { say('Unable to save in this browser.'); } }
function loadGame() { try { const state=JSON.parse(localStorage.getItem(SAVE_KEY)); if(!state||state.version!==1||!Number.isInteger(state.mapIndex)||!maps[state.mapIndex]) return false; currentMapIndex=state.mapIndex; path=maps[currentMapIndex].path.map(point=>({...point})); pads=maps[currentMapIndex].pads.map(point=>({...point})); pathLength=calculatePathLength(); if(Array.isArray(state.unlockedMaps)) state.unlockedMaps.forEach((value,index)=>{if(index<unlockedMaps.length)unlockedMaps[index]=!!value;}); Object.keys(baseUpgrades).forEach(id=>{if(Number.isFinite(state.baseUpgrades?.[id]))baseUpgrades[id]=Math.max(0,Math.min(getUpgradeMax(id),Math.floor(state.baseUpgrades[id])));}); inventory=freshInventory(); Object.entries(state.inventory||{}).forEach(([id,levels])=>{if(inventory[id]&&Array.isArray(levels))inventory[id]=levels.filter(level=>Number.isInteger(level)&&level>0).map(level=>Math.min(level,getMaxLevel({type:types[id]})));}); const savedLayouts=Array.isArray(state.mapTowerStates)?state.mapTowerStates:null; mapTowerStates.forEach((_,index)=>{mapTowerStates[index]=Array.isArray(savedLayouts?.[index])?savedLayouts[index]:index===currentMapIndex?(state.towers||[]):[];}); restoreTowerLayout(mapTowerStates[currentMapIndex]); gold=Math.max(0,Math.floor(state.gold||0)); lives=Math.max(1,Math.floor(state.lives||getStartingLives())); wave=Math.max(0,Math.floor(state.wave||0)); drawCost=Math.max(BASE_DRAW_COST,Math.floor(state.drawCost||BASE_DRAW_COST)); enemies=Array.isArray(state.enemies)?state.enemies.map(restoreSavedEnemy).filter(Boolean):[]; spawnQueue=Array.isArray(state.spawnQueue)?state.spawnQueue.filter(Number.isInteger):[]; spawnCooldown=Math.max(0,Number(state.spawnCooldown)||0); running=!!state.running&&(enemies.length>0||spawnQueue.length>0); autoWave=!!state.autoWave; selected=inventory[state.selected]?.length?state.selected:Object.keys(inventory).find(id=>inventory[id].length)||null; camera.x=Math.max(0,Math.min(W,state.camera?.x||W/2));camera.y=Math.max(0,Math.min(H,state.camera?.y||H/2));camera.zoom=Math.max(.7,Math.min(2.2,state.camera?.zoom||1));gameOver=false;ui.waveButton.disabled=running;ui.waveButton.textContent=running?'DEFENDING':wave?'NEXT WAVE >':'START WAVE >';return true; } catch { return false; } }
function updateCamera(dt) { const left=cameraKeys.has('a'), right=cameraKeys.has('d'), up=cameraKeys.has('w'), down=cameraKeys.has('s'); if(!left&&!right&&!up&&!down) return; const length=Math.hypot((right?1:0)-(left?1:0),(down?1:0)-(up?1:0))||1, speed=460/camera.zoom; camera.x+=((right?1:0)-(left?1:0))/length*speed*dt; camera.y+=((down?1:0)-(up?1:0))/length*speed*dt; camera.x=Math.max(0,Math.min(W,camera.x)); camera.y=Math.max(0,Math.min(H,camera.y)); }

function renderInventory() {
  const categories=[['all','ALL'],['spark','ELECTRIC'],['cannon','CANNON'],['thorns','THORNS']];
  if(ui.towerCategories)ui.towerCategories.innerHTML=categories.map(([id,label])=>`<button data-category="${id}" class="${towerCategory===id?'active':''}" title="Show ${label.toLowerCase()} towers">${label}</button>`).join('');
  ui.inventory.innerHTML = Object.entries(types).filter(([,type])=>towerCategory==='all'||type.kind===towerCategory).map(([id, type]) => {
    const levels = inventory[id], amount = levels.length, highest = amount ? Math.max(...levels) : 0;
    return `<button class="inventory-slot ${selected === id ? 'selected' : ''}" data-tower="${id}" ${amount ? '' : 'disabled'}><span class="inventory-icon ${type.kind}">${type.icon}</span><span class="inventory-name">${type.name}</span><span class="inventory-grade grade-${type.grade}">${type.gradeLabel}</span><span class="inventory-count">OWNED <b>${amount}</b>${highest > 1 ? ` | MAX L${highest}` : ''}</span></button>`;
  }).join('');
}
function renderIndex() { if(!ui.indexPanel) return; const towerCards=Object.values(types).map(type=>`<article class="index-card"><span class="index-icon ${type.kind}" style="--index-color:${type.color}">${type.icon}</span><span><b>${type.name}</b><small>${getAbilityText({type,level:1})}</small></span></article>`).join(''); const enemyCards=[...enemyTypes.map(type=>({...type,group:'NORMAL'})),...eliteTypes.map(type=>({...type,group:'ELITE'})),{...wave30Boss,group:'BOSS'}].map(type=>{const mark=type.name.split(' ').map(word=>word[0]).join('').slice(0,3);return `<article class="index-card enemy"><span class="index-enemy-avatar ${type.group.toLowerCase()}" style="--enemy-body:${type.body};--enemy-top:${type.top}"><i>${mark}</i></span><span><b>${type.name} <em>${type.group}</em></b><small>KEEP DMG ${type.damage} | SPD ${type.speed}</small></span></article>`;}).join(''); ui.indexPanel.innerHTML=`<div class="index-head"><strong>GAME INDEX</strong><button data-close-index>CLOSE</button></div><div class="index-scroll"><h3>TOWERS · ${Object.keys(types).length}</h3><div class="index-grid">${towerCards}</div><h3>ENEMIES · ${enemyTypes.length+eliteTypes.length+1}</h3><div class="index-grid">${enemyCards}</div></div>`; }
function renderStats() { if(!ui.statsPanel) return; const cards=[['TOTAL KILLS',overallStats.kills],['NORMAL KILLS',overallStats.normalKills],['ELITE KILLS',overallStats.eliteKills],['BOSS KILLS',overallStats.bossKills],['SUPPLIES EARNED',overallStats.suppliesEarned],['ROULETTE DRAWS',overallStats.draws],['WAVES CLEARED',overallStats.wavesCleared],['HIGHEST WAVE',overallStats.highestWave],['DEFEATS',overallStats.deaths]]; ui.statsPanel.innerHTML=`<div class="stats-head"><strong>OVERALL STATS</strong><button data-close-stats>CLOSE</button></div><div class="stats-grid">${cards.map(([label,value])=>`<article><small>${label}</small><b>${value.toLocaleString()}</b></article>`).join('')}</div><p>Saved automatically in this browser.</p>`; }
function upgradeCost(tower) { return tower.level * 90; }
function getMaxLevel(tower) { return 3 + grades.findIndex(grade => grade.id === tower.type.grade); }
function getNextGradeType(tower) { const currentGrade=grades.findIndex(grade=>grade.id===tower.type.grade), archetype=archetypes.find(entry=>entry.id===tower.type.id.slice(tower.type.grade.length+1)); return currentGrade<grades.length-1&&archetype?types[`${grades[currentGrade+1].id}-${archetype.id}`]:null; }
function getStartingLives() { return 20 + baseUpgrades.fortify * 5; }
function getRouletteLevel() { return baseUpgrades.roulette + 1; }
function getUpgradeMax(id) { return id==='roulette'?39:id==='slots'?Math.max(...maps.map(map=>map.pads.length-BASE_INSTALL_SLOTS)):10; }
function getMapSlotUpgradeCap(mapIndex=currentMapIndex) { return maps[mapIndex].pads.length-BASE_INSTALL_SLOTS; }
function getOpenBuildPadCount() { return Math.min(pads.length,BASE_INSTALL_SLOTS+baseUpgrades.slots); }
function isPadUnlocked(pad) { return !!pad.tower||pads.indexOf(pad)<getOpenBuildPadCount(); }
function getStageDifficulty() { return maps[currentMapIndex].stage; }
function getDifficultyLabel() { return ['NORMAL','HARD','EXTREME'][getStageDifficulty()-1]; }
function getGradeChance(grade) { const luck=baseUpgrades.luck; if(grade.id==='common') return Math.max(10,50-luck*4); if(grade.id==='uncommon') return Math.max(8,26-luck); if(grade.id==='rare') return 14+luck*2; if(grade.id==='epic') return 7+luck*2; if(grade.id==='legendary') return 3+luck; return grade.chance+luck*.12; }
function getTowerRange(tower) { return tower.type.range + (tower.level - 1) * 18; }
function getTowerDamage(tower) { return Math.round(tower.type.damage * (1 + (tower.level - 1) * .55) * (1 + baseUpgrades.power * .1)); }
function getTowerFireRate(tower) { return tower.type.fireRate * Math.pow(.86, tower.level - 1); }
function getGradeTier(tower) { return grades.findIndex(grade=>grade.id===tower.type.grade); }
function getAbilityText(tower) { const tier=getGradeTier(tower), bonus=tier+1; switch(tower.type.ability){case'chain':return `CHAIN ×${bonus}`;case'shock':return `SHOCK SLOW ${Math.round((.45+tier*.12)*100)/100}s`;case'prism':return `PRISM SPLIT ×${bonus}`;case'storm':return `STORM CHAIN ×${bonus+1}`;case'splash':return `ROOT SPLASH ${42+tier*10}`;case'mortar':return `MORTAR SPLASH ${68+tier*12}`;case'burn':return `BURN ${2+tier*.4}s`;case'root':return `ROOT SLOW ${Math.round((.35+tier*.1)*100)/100}s`;case'freeze':return `FREEZE ${Math.round((.7+tier*.12)*100)/100}s`;case'poison':return `POISON ${2+tier*.35}s`;default:return 'TOWER SKILL';} }
function matchingTower(tower) { return towers.find(other => other !== tower && other.type.id === tower.type.id && other.level === tower.level); }
function renderUpgradePanel() {
  if(!selectedTower || !towers.includes(selectedTower)) { ui.upgradePanel.className='upgrade-panel empty'; ui.upgradePanel.innerHTML='<span class="upgrade-title">UPGRADE</span><span class="upgrade-detail">Click an installed tower.</span>'; return; }
  const maxLevel = getMaxLevel(selectedTower), maxed = selectedTower.level >= maxLevel, nextGradeType=getNextGradeType(selectedTower), canFuse=!maxed||!!nextGradeType, cost = upgradeCost(selectedTower), match = matchingTower(selectedTower), fuseLabel=maxed&&nextGradeType?`PROMOTE ${nextGradeType.gradeLabel}`:maxed?'FUSE MAXED':match?'FUSE MATCH':'FUSE NEEDS MATCH';
  ui.upgradePanel.className='upgrade-panel';
  ui.upgradePanel.innerHTML=`<span class="upgrade-title">${selectedTower.type.name} LV ${selectedTower.level}/${maxLevel}</span><span class="upgrade-detail">DMG ${getTowerDamage(selectedTower)} | RNG ${getTowerRange(selectedTower)}</span><span class="upgrade-detail">SKILL: ${getAbilityText(selectedTower)}</span><button data-upgrade ${maxed || gold < cost ? 'disabled' : ''}>${maxed ? 'MAX LEVEL' : `UPGRADE ${cost}`}</button><button data-fuse ${!canFuse || !match ? 'disabled' : ''}>${fuseLabel}</button><button class="store" data-store>STORE TOWER</button>`;
}
function updateUI() { const missingSupplies=Math.max(0,drawCost-gold), rouletteLevel=getRouletteLevel(); ui.gold.textContent = gold; ui.lives.textContent = lives; ui.wave.textContent = wave; if(ui.drawCost) ui.drawCost.textContent = drawCost; if(ui.rouletteLevel) ui.rouletteLevel.textContent=`LV ${rouletteLevel}`; ui.rollButton.title=missingSupplies ? `Tower roulette costs ${drawCost}. Need ${missingSupplies} more supplies.` : rouletteLevel<10 ? `Draw a random tower for ${drawCost} supplies. Epic and Legendary unlock at roulette level 10.` : rouletteLevel<20 ? `Draw a random tower for ${drawCost} supplies. Mythic and Ancient unlock at roulette level 20.` : rouletteLevel<40 ? `Draw a random tower for ${drawCost} supplies. Celestial and higher grades unlock at roulette level 40.` : `Draw a random tower for ${drawCost} supplies`; ui.rollButton.classList.toggle('needs-supplies',!!missingSupplies&&!isDrawing); ui.difficulty.textContent=`S${getStageDifficulty()} ${getDifficultyLabel()}`; renderInventory(); renderUpgradePanel(); updateMapButton(); updateAutoWaveButton(); if(ui.statsPanel&&!ui.statsPanel.hidden)renderStats(); }
function say(message) { ui.toast.textContent = message; ui.toast.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => ui.toast.classList.remove('show'), 1800); }
function distance(a,b) { return Math.hypot(a.x-b.x, a.y-b.y); }
function pointOnPath(progress) { let remaining = progress; for(let i=0;i<path.length-1;i++){ const a=path[i], b=path[i+1], d=distance(a,b); if(remaining<=d){ const t=remaining/d; return {x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,angle:Math.atan2(b.y-a.y,b.x-a.x)}; } remaining-=d; } return {x:path.at(-1).x,y:path.at(-1).y,angle:0}; }
function closestPathPoint(x,y) { let closest=null; for(let i=0;i<path.length-1;i++){const a=path[i],b=path[i+1],dx=b.x-a.x,dy=b.y-a.y,lengthSq=dx*dx+dy*dy,t=Math.max(0,Math.min(1,((x-a.x)*dx+(y-a.y)*dy)/lengthSq)),point={x:a.x+dx*t,y:a.y+dy*t,angle:Math.atan2(dy,dx)};point.distance=distance({x,y},point);if(!closest||point.distance<closest.distance)closest=point;}return closest; }
function calculatePathLength() { return path.slice(0,-1).reduce((sum,p,i) => sum + distance(p,path[i+1]), 0); }
let pathLength = calculatePathLength();

function makeEnemy(index) { const stage=getStageDifficulty(), boss = wave > 0 && wave % 30 === 0 && index === 0, elite = !boss && wave % 4 === 0 && index === 0; const type=boss ? wave30Boss : elite ? eliteTypes[Math.floor(wave/4)%eliteTypes.length] : enemyTypes[(wave*3+index)%enemyTypes.length]; const baseHp=(boss ? 5400+wave*100 : elite ? 310+wave*50 : 58+wave*24)*(1+(stage-1)*.4), hp=Math.round(baseHp*type.hp), damage=type.damage+stage-1; return {progress:PORTAL_PROGRESS, spawnProgress:PORTAL_PROGRESS, speed:(38+wave*3.4)*type.speed*(1+(stage-1)*.1), hp, maxHp:hp, damage, reward:boss ? 500 : elite ? 25 : 10, r:type.r, elite, boss, type, slow:0, slowFactor:1, poison:0, poisonDamage:0, burn:0, burnDamage:0, statusTick:0, hit:0}; }
function startWave() { if(running || gameOver) return; clearTimeout(autoWaveTimer); wave++; recordWaveStats(); running = true; const stage=getStageDifficulty(); spawnQueue = Array.from({length:6+wave*3+(stage-1)*2},(_,i)=>i); spawnCooldown = 0; ui.waveButton.disabled = true; ui.waveButton.textContent = 'DEFENDING'; updateUI(); say(wave % 30 === 0 ? `BOSS WAVE ${wave}: Ancient Bastion approaches!` : `Stage ${stage} - Wave ${wave} has begun!`); }
function getWaveClearBonus() { return 50 + Math.max(0,wave-1)*10; }
function endWave() { running = false; const bonus = getWaveClearBonus(); gold += bonus; recordStats({suppliesEarned:bonus,wavesCleared:1}); ui.waveButton.disabled = false; ui.waveButton.textContent = 'NEXT WAVE >'; updateUI(); say(`Wave ${wave} defended. Supplies +${bonus}`); if(autoWave){ui.waveButton.disabled=true;autoWaveTimer=setTimeout(()=>{if(autoWave&&!running&&!gameOver)startWave();},1200);} }
function showEnd(title, text) { ui.modalTitle.textContent = title; ui.modalText.textContent = text; document.querySelector('#startButton').textContent = 'NEW GAME'; ui.modal.classList.add('open'); }
function renderBaseUpgradeChoices() { const cards=[{id:'luck',icon:'D6',name:'LUCKY DICE',detail:'Better draw odds for Rare and higher-grade towers.'},{id:'fortify',icon:'HP',name:'FORTIFIED KEEP',detail:'Start each new defense with +5 keep health.'},{id:'power',icon:'DMG',name:'BATTLE DOCTRINE',detail:'All tower damage increases by 10%.'},{id:'roulette',icon:'LV',name:'ROULETTE MASTERY',detail:'Epic/Legendary: LV 10. Mythic/Ancient: LV 20. Celestial+: LV 40.'},{id:'slots',icon:'PAD',name:'EXPAND BUILD SLOTS',detail:`Add one build slot. Stage ${getStageDifficulty()} max: ${maps[currentMapIndex].pads.length}.`}]; const nextMap=unlockedMaps.findIndex(unlocked=>!unlocked); if(nextMap!==-1){const addedGrades=nextMap===1?'Mythic and Ancient grades.':'Celestial, Divine, and Transcendent grades.';cards.push({id:'map',icon:'MAP',name:`UNLOCK STAGE ${maps[nextMap].stage}`,detail:`Unlock ${maps[nextMap].name} and ${addedGrades}`,mapIndex:nextMap});} ui.baseUpgradeChoices.innerHTML=cards.map(card=>{const level=baseUpgrades[card.id],slotCap=getMapSlotUpgradeCap(),maxed=card.id==='roulette'?level>=getUpgradeMax('roulette'):card.id==='slots'?level>=slotCap:card.id!=='map'&&level>=10,levelText=card.id==='map'?'UNLOCK':card.id==='roulette'?maxed?'LV 40 MAX':`LV ${getRouletteLevel()} -> ${getRouletteLevel()+1}`:card.id==='slots'?maxed?`S${getStageDifficulty()} ${getOpenBuildPadCount()}/${pads.length} MAX`:`S${getStageDifficulty()} ${getOpenBuildPadCount()}/${pads.length} -> ${getOpenBuildPadCount()+1}/${pads.length}`:maxed?'MAX':`LV ${level} -> ${level+1}`;return `<button data-base-upgrade="${card.id}" ${maxed?'disabled':''}><span class="base-upgrade-icon">${card.icon}</span><span class="base-upgrade-name">${card.name}</span><span class="base-upgrade-detail">${card.detail}</span><span class="base-upgrade-level">${levelText}</span></button>`;}).join(''); }
function showDeathUpgrades() { ui.modalTitle.textContent='KEEP FALLEN'; ui.modalText.textContent='Choose one base upgrade before your next defense.'; ui.startButton.hidden=true; renderBaseUpgradeChoices(); ui.baseUpgradeChoices.hidden=false; ui.modal.classList.add('open'); }
function restartAfterDefeat() { clearTimeout(drawTimer); clearInterval(drawSpinTimer); clearTimeout(autoWaveTimer); autoWave=false; isDrawing=false; ui.rollButton.disabled=false; ui.rollButton.classList.remove('rolling'); setRouletteTower(); drawCost+=DEATH_DRAW_COST_INCREASE; gold=Math.max(gold,drawCost); lives=getStartingLives(); wave=0; running=false; gameOver=false; enemies=[]; shots=[]; particles=[]; spawnQueue=[]; towers.forEach(tower=>{tower.level=1;tower.cooldown=0;tower.pulse=0;}); mapTowerStates.forEach(layout=>layout.forEach(tower=>tower.level=1)); Object.keys(inventory).forEach(id=>{inventory[id]=inventory[id].map(()=>1);}); selected=Object.keys(inventory).find(id=>inventory[id].length)||selected; selectedTower=null; fusionMode=false; resetView(); ui.waveButton.disabled=false; ui.waveButton.textContent='START WAVE >'; updateUI(); }
function chooseBaseUpgrade(id) { if(id==='map'){const nextMap=unlockedMaps.findIndex(unlocked=>!unlocked);if(nextMap===-1)return;unlockedMaps[nextMap]=true;persistPermanentProgress();ui.baseUpgradeChoices.hidden=true;ui.startButton.hidden=false;ui.startButton.textContent='BEGIN DEFENSE';restartAfterDefeat();ui.modal.classList.remove('open');say(`${maps[nextMap].name} unlocked. Towers retained at level 1.`);return;} const max=id==='slots'?getMapSlotUpgradeCap():getUpgradeMax(id); if(baseUpgrades[id]>=max) return; baseUpgrades[id]++; persistPermanentProgress(); ui.baseUpgradeChoices.hidden=true; ui.startButton.hidden=false; ui.startButton.textContent='BEGIN DEFENSE'; restartAfterDefeat(); ui.modal.classList.remove('open'); say(id==='roulette'?`Roulette Mastery is now level ${getRouletteLevel()}.`:id==='slots'?`Build slots expanded: ${getOpenBuildPadCount()}/${pads.length}.`:`${id.toUpperCase()} base upgrade applied. Towers retained at level 1.`); }
function reset() { clearTimeout(drawTimer); clearInterval(drawSpinTimer); clearTimeout(autoWaveTimer); autoWave=false; isDrawing=false; ui.rollButton.disabled=false; ui.rollButton.classList.remove('rolling'); setRouletteTower(); gold=320; lives=getStartingLives(); wave=0; drawCost=BASE_DRAW_COST; running=false; gameOver=false; towers=[]; mapTowerStates.forEach((_,index)=>mapTowerStates[index]=[]); enemies=[]; shots=[]; particles=[]; spawnQueue=[]; inventory=freshInventory(); selected='common-spark-coil'; selectedTower=null; fusionMode=false; resetView(); pads.forEach(p => delete p.tower); ui.waveButton.disabled=false; ui.waveButton.textContent='START WAVE >'; updateUI(); }

function choose(type) { if(!inventory[type] || !inventory[type].length) return say('Draw this tower before selecting it.'); selected = type; renderInventory(); say(`${types[type].name} selected.`); }
function selectTower(tower) { fusionMode=false; selectedTower=tower; renderUpgradePanel(); say(`${tower.type.name} selected. Level ${tower.level}.`); }
function upgradeTower() { if(!selectedTower || !towers.includes(selectedTower)) return; if(selectedTower.level >= getMaxLevel(selectedTower)) return say('This tower is already at max level.'); const cost=upgradeCost(selectedTower); if(gold < cost) return say(`You need ${cost-gold} more supplies to upgrade.`); gold-=cost; selectedTower.level++; updateUI(); say(`${selectedTower.type.name} upgraded to level ${selectedTower.level}!`); }
function startFusion() { if(!selectedTower || (selectedTower.level >= getMaxLevel(selectedTower) && !getNextGradeType(selectedTower))) return; if(!matchingTower(selectedTower)) return say('Fusion needs another tower of the same type and level.'); fusionMode=true; say(`Fusion ready: click another ${selectedTower.type.name} level ${selectedTower.level}.`); }
function fuseWith(tower) { if(!fusionMode || !selectedTower) return; if(tower === selectedTower) return say('Click a different matching tower to fuse.'); if(tower.type.id !== selectedTower.type.id || tower.level !== selectedTower.level) return say('Fusion requires the same tower type and level.'); const promoting=selectedTower.level>=getMaxLevel(selectedTower), nextGradeType=promoting&&getNextGradeType(selectedTower); if(promoting&&!nextGradeType) return say('Transcendent towers are already at the final level cap.'); towers.splice(towers.indexOf(tower),1); if(tower.pad) delete tower.pad.tower; if(nextGradeType){selectedTower.type=nextGradeType;selectedTower.level=1;}else selectedTower.level++; selectedTower.pulse=.55; fusionMode=false; for(let i=0;i<16;i++) particles.push({x:selectedTower.x,y:selectedTower.y,vx:(Math.random()-.5)*180,vy:(Math.random()-.5)*180,life:.6,size:4+Math.random()*4,color:'#ffe779'}); updateUI(); say(nextGradeType?`Fusion promotion! ${selectedTower.type.name} is now level 1.`:`Fusion complete! ${selectedTower.type.name} is now level ${selectedTower.level}.`); }
function storeTower() { if(!selectedTower || !towers.includes(selectedTower)) return; const tower=selectedTower; inventory[tower.type.id].push(tower.level); inventory[tower.type.id].sort((a,b)=>b-a); towers.splice(towers.indexOf(tower),1); if(tower.pad) delete tower.pad.tower; selectedTower=null; fusionMode=false; selected=tower.type.id; updateUI(); say(`${tower.type.name} level ${tower.level} stored in inventory.`); }
function deployThornsOnPath(x,y) { if(!selected || !inventory[selected].length) return say('Select a thorn tower you own in the inventory.'); const type=types[selected], point=closestPathPoint(x,y); if(point.distance>36) return say('Thorn towers must be installed directly on the path.'); if(towers.some(t=>t.pathTrap&&distance(t,point)<44)) return say('Another thorn tower is already too close.'); const level=inventory[selected].sort((a,b)=>b-a).shift(), tower={x:point.x,y:point.y,type,cooldown:Math.random()*.25,angle:point.angle,pulse:0,level,pad:null,pathTrap:true}; towers.push(tower); selectedTower=tower; fusionMode=false; if(!inventory[selected].length) selected=Object.keys(inventory).find(id=>inventory[id].length)||null; updateUI(); say(`${type.name} level ${level} installed on the path.`); }
function buildAt(pad) { if(!selected || !inventory[selected].length) return say('Select a tower you own in the inventory.'); const type = types[selected]; if(type.kind==='thorns') return say('Thorn towers must be installed directly on the path.'); const level=inventory[selected].sort((a,b)=>b-a).shift(); const tower = {x:pad.x,y:pad.y,type,cooldown:Math.random()*.25,angle:-Math.PI/2,pulse:0,level,pad}; pad.tower=tower; towers.push(tower); selectedTower=tower; fusionMode=false; if(!inventory[selected].length) selected = Object.keys(inventory).find(id => inventory[id].length) || null; updateUI(); say(`${type.name} level ${level} installed.`); }
function setRouletteTower(type) { if(!ui.rouletteTower) return; ui.rouletteTower.textContent=type?type.icon:'TWR'; ui.rouletteTower.style.setProperty('--tower-color',type?type.color:'#d5c8f4'); ui.rouletteTower.title=type?type.name:'Tower roulette'; }
function finishRoulette() { clearTimeout(drawTimer); clearInterval(drawSpinTimer); isDrawing=false; ui.rollButton.disabled=false; ui.rollButton.classList.remove('rolling'); }
function getMapGradeCap() { return unlockedMaps[2]?grades.length-1:unlockedMaps[1]?6:4; }
function getRouletteGrades() { const level=getRouletteLevel(); return grades.filter((grade,index)=>index<=getMapGradeCap()&&(level>=10||index<=2)&&(level>=20||index<=4)&&(level>=40||index<=6)); }
function drawTower() { if(isDrawing) return; if(gold < drawCost) return say(`Tower roulette costs ${drawCost}. You need ${drawCost-gold} more supplies.`); const allowedGrades=getRouletteGrades(), previews=Object.values(types).filter(type=>allowedGrades.some(grade=>grade.id===type.grade)); if(!previews.length) return say('No towers are available for the roulette.'); const cost=drawCost; isDrawing=true; gold-=cost; recordStats({draws:1}); ui.rollButton.disabled=true; ui.rollButton.classList.add('rolling'); updateUI(); try { setRouletteTower(previews[Math.floor(Math.random()*previews.length)]); drawSpinTimer=setInterval(()=>{setRouletteTower(previews[Math.floor(Math.random()*previews.length)]);},65); drawTimer=setTimeout(()=>{try { let roll=Math.random()*allowedGrades.reduce((sum,grade)=>sum+getGradeChance(grade),0), grade=allowedGrades[0]; for(const entry of allowedGrades){roll-=getGradeChance(entry);if(roll<=0){grade=entry;break;}} const candidates=previews.filter(type=>type.grade===grade.id); const drawn=candidates[Math.floor(Math.random()*candidates.length)]; if(!drawn) throw new Error('roulette result missing'); setRouletteTower(drawn); inventory[drawn.id].push(1); selected=drawn.id;towerCategory=drawn.kind; say(`Tower roulette: ${drawn.name}!`); } catch { gold+=cost; say('Roulette error recovered. Your supplies were refunded.'); } finally { finishRoulette(); updateUI(); } },850); } catch { gold+=cost; finishRoulette(); updateUI(); say('Roulette error recovered. Your supplies were refunded.'); } }

function eventToWorld(event) { const rect=canvas.getBoundingClientRect(), screenX=(event.clientX-rect.left)*W/rect.width, screenY=(event.clientY-rect.top)*H/rect.height; return {x:(screenX-W/2)/camera.zoom+camera.x, y:(screenY-H/2)/camera.zoom+camera.y, screenX, screenY}; }
canvas.addEventListener('click', event => { if(gameOver) return; const {x,y}=eventToWorld(event), pad=pads.find(p=>distance({x,y},p)<36), selectedType=selected&&types[selected]; if(pad){if(!isPadUnlocked(pad)) return say(`Build slot locked. Upgrade slots after defeat (${getOpenBuildPadCount()}/${pads.length}).`);if(pad.tower) return fusionMode ? fuseWith(pad.tower) : selectTower(pad.tower); if(fusionMode) return say('Fusion needs a matching installed tower.'); return buildAt(pad);} const pathTower=towers.find(t=>t.pathTrap&&distance({x,y},t)<28); if(pathTower) return fusionMode ? fuseWith(pathTower) : selectTower(pathTower); if(fusionMode) return say('Fusion needs a matching installed tower.'); if(selectedType&&selectedType.kind==='thorns') return deployThornsOnPath(x,y); say('Click a glowing hexagonal build zone.'); });
canvas.addEventListener('wheel', event => { event.preventDefault(); const before=eventToWorld(event), nextZoom=Math.max(.7,Math.min(2.2,camera.zoom*(event.deltaY>0?.9:1.1))); if(nextZoom===camera.zoom) return; camera.zoom=nextZoom; const after=eventToWorld(event); camera.x+=before.x-after.x; camera.y+=before.y-after.y; }, {passive:false});
ui.inventory.addEventListener('click', event => { const slot = event.target.closest('button[data-tower]'); if(slot) choose(slot.dataset.tower); });
if(ui.towerCategories) ui.towerCategories.addEventListener('click', event => { const button=event.target.closest('[data-category]'); if(!button) return; towerCategory=button.dataset.category; renderInventory(); say(`${button.textContent} tower category selected.`); });
ui.inventory.addEventListener('wheel', event => { event.preventDefault(); ui.inventory.scrollLeft += event.deltaY + event.deltaX; }, {passive:false});
ui.upgradePanel.addEventListener('click', event => { if(event.target.closest('[data-upgrade]')) upgradeTower(); if(event.target.closest('[data-fuse]')) startFusion(); if(event.target.closest('[data-store]')) storeTower(); });
ui.baseUpgradeChoices.addEventListener('click', event => { const button=event.target.closest('[data-base-upgrade]'); if(button) chooseBaseUpgrade(button.dataset.baseUpgrade); });
ui.resetViewButton.addEventListener('click', () => { resetView(); say('View reset.'); });
ui.mapButton.addEventListener('click', () => { setMap((currentMapIndex+1)%maps.length); });
if(ui.previousMapButton) ui.previousMapButton.addEventListener('click', () => { setMap((currentMapIndex-1+maps.length)%maps.length); });
ui.saveButton.addEventListener('click', saveGame);
if(ui.indexButton) ui.indexButton.addEventListener('click', () => { const opening=ui.indexPanel.hidden; ui.indexPanel.hidden=!opening; if(opening) renderIndex(); });
if(ui.indexPanel) ui.indexPanel.addEventListener('click', event => { if(event.target.closest('[data-close-index]')) ui.indexPanel.hidden=true; });
if(ui.statsButton) ui.statsButton.addEventListener('click', () => { const opening=ui.statsPanel.hidden; ui.statsPanel.hidden=!opening; if(opening) renderStats(); });
if(ui.statsPanel) ui.statsPanel.addEventListener('click', event => { if(event.target.closest('[data-close-stats]')) ui.statsPanel.hidden=true; });
ui.autoWaveButton.addEventListener('click', () => { autoWave=!autoWave; clearTimeout(autoWaveTimer); updateAutoWaveButton(); say(`Auto wave ${autoWave?'enabled':'disabled'}.`); if(autoWave&&!running&&!gameOver) startWave(); });
ui.waveButton.addEventListener('click', startWave); ui.rollButton.addEventListener('click', drawTower);
ui.startButton.addEventListener('click', () => { if(gameOver) reset(); ui.baseUpgradeChoices.hidden=true; ui.modal.classList.remove('open'); });
window.addEventListener('keydown', e => { const key=e.key.toLowerCase(); if(['w','a','s','d'].includes(key)){cameraKeys.add(key);e.preventDefault();} if(e.key === ' '){ e.preventDefault(); startWave(); } if(['1','2','3'].includes(e.key)) choose(['common-spark-coil','common-root-cannon','common-thorn-garden'][+e.key-1]); });
window.addEventListener('keyup', e => { cameraKeys.delete(e.key.toLowerCase()); });

function hurt(enemy, amount, color) { enemy.hp -= amount; enemy.hit = .12; for(let i=0;i<5;i++) particles.push({x:enemy.x,y:enemy.y,vx:(Math.random()-.5)*90,vy:(Math.random()-.5)*90,life:.35,size:2+Math.random()*3,color}); if(enemy.hp <= 0){ gold += enemy.reward; recordStats({kills:1,normalKills:enemy.boss||enemy.elite?0:1,eliteKills:enemy.elite?1:0,bossKills:enemy.boss?1:0,suppliesEarned:enemy.reward}); particles.push({x:enemy.x,y:enemy.y,vx:0,vy:0,life:.55,size:enemy.r*2.6,color:'#ffe779',burst:true}); enemies.splice(enemies.indexOf(enemy),1); if(enemy.boss){const upgraded=baseUpgrades.roulette<getUpgradeMax('roulette')&&Math.random()<.5;if(upgraded){baseUpgrades.roulette++;persistPermanentProgress();}say(upgraded?`BOSS DEFEATED! +500 supplies. Roulette Mastery is now LV ${getRouletteLevel()}!`:`BOSS DEFEATED! +500 supplies. Roulette Mastery stayed at LV ${getRouletteLevel()}.`);} updateUI(); } }
function applySlow(enemy, duration, factor) { enemy.slow=Math.max(enemy.slow||0,duration); enemy.slowFactor=Math.min(enemy.slowFactor||1,factor); }
function applyDot(enemy, kind, duration, damage) { enemy[kind]=Math.max(enemy[kind]||0,duration); enemy[`${kind}Damage`]=Math.max(enemy[`${kind}Damage`]||0,damage); enemy.statusTick=0; }
function nearbyEnemies(target, radius, count) { return enemies.filter(enemy=>enemy!==target&&distance(enemy,target)<radius).sort((a,b)=>b.progress-a.progress).slice(0,count); }
function applyThornAbility(tower, enemy) { const tier=getGradeTier(tower); if(tower.type.ability==='root') applySlow(enemy,.35+tier*.1,.74-tier*.035); if(tower.type.ability==='freeze') applySlow(enemy,.7+tier*.12,.54-tier*.035); if(tower.type.ability==='poison') applyDot(enemy,'poison',2+tier*.35,getTowerDamage(tower)*(.16+tier*.035)); }
function triggerShotAbility(shot) { const tier=getGradeTier(shot.tower), ability=shot.tower.type.ability, target=shot.target, targetAlive=enemies.includes(target); if(ability==='chain') nearbyEnemies(target,70,1+tier).forEach(enemy=>hurt(enemy,shot.damage*(.42+tier*.035),shot.color)); if(ability==='shock'&&targetAlive) applySlow(target,.45+tier*.12,.7-tier*.035); if(ability==='prism') nearbyEnemies(target,92,1+tier).forEach(enemy=>hurt(enemy,shot.damage*(.48+tier*.035),shot.color)); if(ability==='storm') nearbyEnemies(target,98,2+tier).forEach(enemy=>hurt(enemy,shot.damage*(.5+tier*.035),shot.color)); if(ability==='splash') nearbyEnemies(target,42+tier*10,99).forEach(enemy=>hurt(enemy,shot.damage*(.5+tier*.03),shot.color)); if(ability==='mortar') nearbyEnemies(target,68+tier*12,99).forEach(enemy=>hurt(enemy,shot.damage*(.62+tier*.035),shot.color)); if(ability==='burn'&&targetAlive) applyDot(target,'burn',2+tier*.4,shot.damage*(.22+tier*.04)); }
function update(dt) {
  if(running && spawnQueue.length){ spawnCooldown -= dt; if(spawnCooldown <= 0){ enemies.push(makeEnemy(spawnQueue.shift())); spawnCooldown = .58; } }
  for(const enemy of [...enemies]) { enemy.poison=Math.max(0,(enemy.poison||0)-dt); enemy.burn=Math.max(0,(enemy.burn||0)-dt); enemy.statusTick=(enemy.statusTick||0)-dt; if(enemy.statusTick<=0&&(enemy.poison>0||enemy.burn>0)){enemy.statusTick=.35;const dotDamage=(enemy.poison>0?enemy.poisonDamage:0)+(enemy.burn>0?enemy.burnDamage:0);hurt(enemy,dotDamage*.35,enemy.burn>0?'#ff9d55':'#ae7cff');if(!enemies.includes(enemy))continue;} enemy.progress=Math.max(enemy.spawnProgress,enemy.progress+enemy.speed*dt*(enemy.slow > 0 ? enemy.slowFactor||.62 : 1)); enemy.slow=Math.max(0,enemy.slow-dt); if(!enemy.slow) enemy.slowFactor=1; enemy.hit=Math.max(0,enemy.hit-dt); const pos=pointOnPath(enemy.progress); enemy.x=pos.x; enemy.y=pos.y; enemy.angle=pos.angle; if(enemy.progress >= pathLength){ enemies.splice(enemies.indexOf(enemy),1); lives=Math.max(0,lives-enemy.damage); updateUI(); say(`${enemy.type.name} hit the keep for ${enemy.damage} damage!`); if(lives <= 0){ gameOver=true; running=false; recordStats({deaths:1}); showDeathUpgrades(); } } }
  for(const tower of towers) { tower.cooldown -= dt; tower.pulse=Math.max(0,tower.pulse-dt); const range=getTowerRange(tower), targets=enemies.filter(e=>distance(tower,e)<range); if(!targets.length) continue; const target=targets.reduce((best,e)=>e.progress>best.progress?e:best,targets[0]); tower.angle=Math.atan2(target.y-tower.y,target.x-tower.x); if(tower.type.kind === 'thorns'){ if(tower.cooldown <= 0){ targets.filter(e=>distance(tower,e)<range).forEach(enemy=>{applyThornAbility(tower,enemy);hurt(enemy,getTowerDamage(tower),tower.type.color);}); tower.cooldown=getTowerFireRate(tower); tower.pulse=.25; } } else if(tower.cooldown <= 0){ tower.cooldown=getTowerFireRate(tower); tower.pulse=.15; shots.push({x:tower.x,y:tower.y,target,tower,damage:getTowerDamage(tower),color:tower.type.color,kind:tower.type.kind,speed:tower.type.kind === 'spark' ? 720 : 410}); } }
  for(const shot of [...shots]) { if(!enemies.includes(shot.target)){ shots.splice(shots.indexOf(shot),1); continue; } const dx=shot.target.x-shot.x,dy=shot.target.y-shot.y,d=Math.hypot(dx,dy),move=shot.speed*dt; if(d < move+shot.target.r){ hurt(shot.target,shot.damage,shot.color); triggerShotAbility(shot); shots.splice(shots.indexOf(shot),1); } else { shot.x+=dx/d*move; shot.y+=dy/d*move; } }
  for(const p of particles){ p.life-=dt; p.x+=p.vx*dt; p.y+=p.vy*dt; p.vx*=.92; p.vy*=.92; } particles=particles.filter(p=>p.life>0);
  if(running && !spawnQueue.length && !enemies.length) endWave();
}

function hex(x,y,r,fill,stroke) { ctx.beginPath(); for(let i=0;i<6;i++){const a=Math.PI/3*i+Math.PI/6,px=x+Math.cos(a)*r,py=y+Math.sin(a)*r; i?ctx.lineTo(px,py):ctx.moveTo(px,py);} ctx.closePath(); ctx.fillStyle=fill; ctx.fill(); if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke();} }
function drawTree(x,y,size) { ctx.save();ctx.translate(x,y);ctx.fillStyle='#533b28';ctx.fillRect(-size*.13,0,size*.26,size*.58);ctx.fillStyle='#173f35';ctx.beginPath();ctx.arc(0,-size*.05,size*.65,0,Math.PI*2);ctx.fill();ctx.fillStyle='#28694a';ctx.beginPath();ctx.arc(-size*.22,-size*.24,size*.46,0,Math.PI*2);ctx.arc(size*.27,-size*.2,size*.43,0,Math.PI*2);ctx.arc(0,-size*.48,size*.42,0,Math.PI*2);ctx.fill();ctx.fillStyle='#53a461';ctx.beginPath();ctx.arc(-size*.17,-size*.43,size*.22,0,Math.PI*2);ctx.arc(size*.27,-size*.31,size*.17,0,Math.PI*2);ctx.fill();ctx.restore(); }
function drawRock(x,y,size) { ctx.save();ctx.translate(x,y);ctx.fillStyle='#344d53';ctx.beginPath();ctx.moveTo(-size*.8,size*.45);ctx.lineTo(-size*.55,-size*.4);ctx.lineTo(size*.15,-size*.7);ctx.lineTo(size*.75,-size*.18);ctx.lineTo(size*.62,size*.52);ctx.closePath();ctx.fill();ctx.fillStyle='#688084';ctx.beginPath();ctx.moveTo(-size*.45,-size*.3);ctx.lineTo(size*.12,-size*.56);ctx.lineTo(size*.45,-size*.19);ctx.lineTo(-size*.1,-size*.02);ctx.closePath();ctx.fill();ctx.restore(); }
function drawScenery() { const theme=maps[currentMapIndex].theme;ctx.fillStyle=theme.water;ctx.fillRect(0,0,W,68);ctx.fillStyle='#d8f7f2';for(let x=10;x<W;x+=58){const y=31+Math.sin((x+performance.now()/24)/75)*3;ctx.fillRect(x,y,29,3);}ctx.fillStyle=theme.shore;ctx.fillRect(0,65,W,9);ctx.fillStyle='#9d8158';ctx.fillRect(0,73,W,4);[[48,96,27],[105,75,22],[318,72,24],[430,88,20],[700,76,28],[1080,83,25],[74,598,33],[177,620,24],[355,609,28],[650,614,25],[908,625,32],[1035,607,28]].forEach(tree=>drawTree(...tree));[[24,208,18],[56,525,21],[275,622,15],[585,628,20],[820,624,18],[1034,194,22],[1064,417,17]].forEach(rock=>drawRock(...rock)); }
function drawMap() { const theme=maps[currentMapIndex].theme;ctx.fillStyle=theme.grass; ctx.fillRect(0,0,W,H); for(let x=0;x<W;x+=42) for(let y=0;y<H;y+=42){ctx.fillStyle=(x/42+y/42)%2?theme.grassAlt:theme.grass;ctx.fillRect(x+1,y+1,40,40);} drawScenery(); ctx.strokeStyle='#6a594d';ctx.lineWidth=66;ctx.lineJoin='round';ctx.lineCap='round';ctx.beginPath();ctx.moveTo(path[0].x,path[0].y);path.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.stroke();ctx.strokeStyle='#c6ad83';ctx.lineWidth=51;ctx.stroke();ctx.strokeStyle='#e2cea6';ctx.lineWidth=2;ctx.setLineDash([7,11]);ctx.stroke();ctx.setLineDash([]); ctx.fillStyle='#173d40';ctx.fillRect(938,28,130,108);ctx.fillStyle='#276067';ctx.fillRect(946,36,114,92);ctx.fillStyle='#ffe374';ctx.font='bold 14px system-ui';ctx.fillText('FORTUNE KEEP',955,81);ctx.fillStyle='#91ecbd';ctx.fillRect(987,96,34,32); for(const pad of pads){const occupied=pad.tower;hex(pad.x,pad.y,28,occupied?'#37595b':'#65c78b',occupied?'#1f3638':'#c1ffd0');if(!occupied){ctx.globalAlpha=.2+Math.sin(performance.now()/280+pad.x)*.12;hex(pad.x,pad.y,37,'#adffcb');ctx.globalAlpha=1;}} }
function drawPortal() { const portal=pointOnPath(PORTAL_PROGRESS), active=running||spawnQueue.length>0, time=performance.now()/1000, pulse=1+Math.sin(time*5)*.11;ctx.save();ctx.translate(portal.x,portal.y);ctx.scale(1,pulse);ctx.fillStyle=active?'#5e27a9':'#2b466b';ctx.globalAlpha=.32;ctx.beginPath();ctx.arc(0,0,31,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle=active?'#e8a4ff':'#8ab4dc';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,23,0,Math.PI*2);ctx.stroke();ctx.strokeStyle=active?'#8eebff':'#517fa5';ctx.lineWidth=2;ctx.setLineDash([7,5]);ctx.rotate(active?time*2:0);ctx.beginPath();ctx.arc(0,0,16,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=active?'#c76bff':'#426c94';ctx.beginPath();ctx.arc(0,0,11,0,Math.PI*2);ctx.fill();if(active){for(let i=0;i<4;i++){const angle=time*3+i*Math.PI/2;ctx.fillStyle='#f4c4ff';ctx.beginPath();ctx.arc(Math.cos(angle)*29,Math.sin(angle)*29,3,0,Math.PI*2);ctx.fill();}}ctx.restore();ctx.fillStyle=active?'#ffe0ff':'#d4e7ff';ctx.font='bold 9px system-ui';ctx.fillText(active?'PORTAL ACTIVE':'PORTAL',portal.x-26,portal.y-38); }
function drawGradeEffect(t) {
  const tier=grades.findIndex(grade=>grade.id===t.type.grade), time=performance.now()/1000;
  if(tier<1) return;
  ctx.save();ctx.globalCompositeOperation='lighter';ctx.strokeStyle=t.type.color;
  if(tier>=1){ctx.globalAlpha=.16+.05*Math.sin(time*3+t.x);ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,27+Math.sin(time*3+t.y)*2,0,Math.PI*2);ctx.stroke();}
  if(tier>=2){for(let i=0;i<3;i++){const a=time*1.8+i*Math.PI*2/3;ctx.globalAlpha=.7;ctx.fillStyle=t.type.color;ctx.beginPath();ctx.arc(Math.cos(a)*30,Math.sin(a)*30,3,0,Math.PI*2);ctx.fill();}}
  if(tier>=3){ctx.globalAlpha=.38;ctx.lineWidth=2;ctx.setLineDash([5,4]);ctx.rotate(-time*.9);ctx.beginPath();ctx.arc(0,0,35,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);}
  if(tier>=4){ctx.globalAlpha=.55;ctx.lineWidth=2;for(let i=0;i<8;i++){const a=time*1.6+i*Math.PI/4;ctx.beginPath();ctx.moveTo(Math.cos(a)*25,Math.sin(a)*25);ctx.lineTo(Math.cos(a)*42,Math.sin(a)*42);ctx.stroke();}ctx.globalAlpha=.25+.15*Math.sin(time*5);ctx.fillStyle='#fff6ad';ctx.beginPath();ctx.arc(0,0,38,0,Math.PI*2);ctx.fill();}
  ctx.restore();
}
function drawGradeCrest(t) {
  const tier=getGradeTier(t), color=t.type.color, time=performance.now()/1000, diamond=(x,y,size)=>{ctx.beginPath();ctx.moveTo(x,y-size);ctx.lineTo(x+size,y);ctx.lineTo(x,y+size);ctx.lineTo(x-size,y);ctx.closePath();ctx.fill();};
  if(tier<1) return;
  ctx.save();ctx.globalCompositeOperation='lighter';ctx.fillStyle=color;ctx.strokeStyle=color;
  if(tier>=1){ctx.globalAlpha=.7;ctx.fillRect(-14,-27,28,4);}
  if(tier>=2){ctx.globalAlpha=.85;diamond(-22,0,5);diamond(22,0,5);}
  if(tier>=3){ctx.globalAlpha=.9;ctx.beginPath();ctx.moveTo(-13,-24);ctx.lineTo(-6,-37);ctx.lineTo(0,-27);ctx.lineTo(7,-39);ctx.lineTo(15,-24);ctx.closePath();ctx.fill();}
  if(tier>=4){ctx.globalAlpha=.75;ctx.beginPath();ctx.moveTo(-20,-7);ctx.lineTo(-43,-20);ctx.lineTo(-31,2);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(20,-7);ctx.lineTo(43,-20);ctx.lineTo(31,2);ctx.closePath();ctx.fill();}
  if(tier>=5){ctx.globalAlpha=.8;ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,31,-.9,.9);ctx.stroke();diamond(0,-37,5);}
  if(tier>=6){ctx.globalAlpha=.7;ctx.lineWidth=2;ctx.setLineDash([3,4]);ctx.rotate(time*.45);ctx.beginPath();for(let i=0;i<6;i++){const a=i*Math.PI/3, x=Math.cos(a)*40,y=Math.sin(a)*40;i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.closePath();ctx.stroke();ctx.setLineDash([]);}
  if(tier>=7){ctx.globalAlpha=.92;for(let i=0;i<5;i++){const a=time*.8+i*Math.PI*2/5;diamond(Math.cos(a)*42,Math.sin(a)*42,4);}}
  if(tier>=8){ctx.globalAlpha=.75;ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,46,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(-50,0);ctx.lineTo(50,0);ctx.moveTo(0,-50);ctx.lineTo(0,50);ctx.stroke();}
  if(tier>=9){ctx.globalAlpha=.9;ctx.lineWidth=3;for(let i=0;i<12;i++){const a=time*1.2+i*Math.PI/6;ctx.beginPath();ctx.moveTo(Math.cos(a)*36,Math.sin(a)*36);ctx.lineTo(Math.cos(a)*58,Math.sin(a)*58);ctx.stroke();}}
  ctx.restore();
}
function drawPlacedTower(t) {
  ctx.save(); ctx.translate(t.x,t.y);
  drawGradeEffect(t);
  if(t===selectedTower){const range=getTowerRange(t);ctx.globalAlpha=.14;ctx.fillStyle=t.type.color;ctx.beginPath();ctx.arc(0,0,range,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.72;ctx.strokeStyle=t.type.color;ctx.lineWidth=2;ctx.setLineDash([8,7]);ctx.beginPath();ctx.arc(0,0,range,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;ctx.strokeStyle='#ffe96b';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,30,0,Math.PI*2);ctx.stroke();}
  const tier=getGradeTier(t), model=t.type.modelId||t.type.id.slice(t.type.grade.length+1); drawGradeCrest(t); ctx.scale(1+tier*.028,1+tier*.028);
  if(t.type.kind==='thorns'){
    if(model==='thorn-garden'){
      ctx.fillStyle='#385d2f';ctx.beginPath();for(let i=0;i<7;i++){const a=i*Math.PI*2/7;ctx.lineTo(Math.cos(a)*19,Math.sin(a)*19);}ctx.fill();ctx.fillStyle='#c9ff82';for(let i=0;i<6;i++){ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(Math.cos(i*Math.PI/3)*23,Math.sin(i*Math.PI/3)*23);ctx.lineTo(Math.cos(i*Math.PI/3+.32)*10,Math.sin(i*Math.PI/3+.32)*10);ctx.fill();}
    } else if(model==='frost-bramble'){
      ctx.fillStyle='#2c5f70';ctx.beginPath();ctx.arc(0,0,19,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#d9fcff';ctx.lineWidth=3;for(let i=0;i<6;i++){const a=i*Math.PI/3;ctx.beginPath();ctx.moveTo(Math.cos(a)*5,Math.sin(a)*5);ctx.lineTo(Math.cos(a)*25,Math.sin(a)*25);ctx.lineTo(Math.cos(a+.22)*13,Math.sin(a+.22)*13);ctx.stroke();}ctx.fillStyle='#9df4ff';ctx.beginPath();ctx.arc(0,0,8,0,Math.PI*2);ctx.fill();
    } else {
      ctx.fillStyle='#315a32';ctx.beginPath();ctx.arc(0,0,20,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#b0e66c';ctx.lineWidth=4;ctx.beginPath();ctx.arc(-7,2,13,-1.8,1);ctx.arc(8,-2,12,1.1,4.2);ctx.stroke();ctx.fillStyle='#b97cff';for(let i=0;i<4;i++){const a=i*Math.PI/2+.35;ctx.beginPath();ctx.arc(Math.cos(a)*13,Math.sin(a)*13,5,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#d8ff91';ctx.beginPath();ctx.arc(0,0,6,0,Math.PI*2);ctx.fill();
    }
  } else {
    ctx.fillStyle='#294c58';ctx.beginPath();ctx.arc(0,0,22,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#9fd3d6';ctx.lineWidth=3;ctx.stroke();ctx.rotate(t.angle);
    if(model==='spark-coil'){
      ctx.fillStyle='#1a4652';ctx.fillRect(-5,-12,16,24);ctx.strokeStyle='#9fe9e7';ctx.lineWidth=2;ctx.strokeRect(-5,-12,16,24);ctx.fillStyle='#59c7d1';ctx.fillRect(-1,-8,8,16);ctx.strokeStyle='#fff17b';ctx.lineWidth=3;for(let y=-8;y<=8;y+=8){ctx.beginPath();ctx.moveTo(4,y);ctx.lineTo(13,y);ctx.lineTo(19,y+4);ctx.lineTo(24,y);ctx.stroke();}ctx.fillStyle='#fff2a6';ctx.beginPath();ctx.arc(25,0,5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#47d9e6';ctx.beginPath();ctx.arc(2,0,4,0,Math.PI*2);ctx.fill();
    } else if(model==='arc-beacon'){
      ctx.fillStyle='#6ce4ff';ctx.beginPath();ctx.moveTo(4,0);ctx.lineTo(23,-14);ctx.lineTo(23,14);ctx.closePath();ctx.fill();ctx.fillStyle='#e8ffff';ctx.fillRect(10,-3,19,6);
    } else if(model==='volt-prism'){
      ctx.fillStyle='#bd9bff';ctx.beginPath();ctx.moveTo(4,0);ctx.lineTo(22,-15);ctx.lineTo(32,0);ctx.lineTo(22,15);ctx.closePath();ctx.fill();ctx.strokeStyle='#fff4ff';ctx.lineWidth=2;ctx.stroke();
    } else if(model==='storm-pylon'){
      ctx.strokeStyle='#f3e779';ctx.lineWidth=4;for(let y=-11;y<=11;y+=11){ctx.beginPath();ctx.moveTo(3,y);ctx.lineTo(29,y-8);ctx.stroke();}ctx.fillStyle='#8ae8ff';ctx.fillRect(4,-5,14,10);
    } else if(model==='root-cannon'){
      ctx.fillStyle='#8b6b42';ctx.fillRect(1,-8,31,16);ctx.fillStyle='#c3a36d';ctx.fillRect(22,-5,15,10);ctx.strokeStyle='#4b3526';ctx.lineWidth=3;ctx.strokeRect(1,-8,31,16);
    } else if(model==='bastion-mortar'){
      ctx.fillStyle='#7f949f';ctx.beginPath();ctx.arc(8,0,14,0,Math.PI*2);ctx.fill();ctx.fillStyle='#bdced4';ctx.beginPath();ctx.arc(20,0,13,Math.PI*.75,Math.PI*1.25);ctx.lineTo(31,-7);ctx.lineTo(31,7);ctx.closePath();ctx.fill();ctx.strokeStyle='#273e49';ctx.lineWidth=3;ctx.stroke();
    } else {
      ctx.fillStyle='#ad4d35';ctx.fillRect(0,-9,34,18);ctx.fillStyle='#ffbb57';ctx.fillRect(25,-5,18,10);ctx.fillStyle='#ffed8b';ctx.beginPath();ctx.moveTo(41,0);ctx.lineTo(51,-8);ctx.lineTo(49,8);ctx.closePath();ctx.fill();ctx.strokeStyle='#562b2d';ctx.lineWidth=3;ctx.strokeRect(0,-9,34,18);
    }
    ctx.fillStyle='#122d38';ctx.beginPath();ctx.arc(0,0,10,0,Math.PI*2);ctx.fill();
  }
  if(t.pulse){ctx.strokeStyle=t.type.color;ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,30,0,Math.PI*2);ctx.stroke();}
  ctx.restore(); ctx.fillStyle='#fff3a1';ctx.font='bold 10px system-ui';ctx.fillText(`L${t.level}`,t.x-8,t.y-30);
}
function drawEnemy(e) { ctx.save();ctx.translate(e.x,e.y);ctx.rotate(e.angle);ctx.fillStyle=e.hit?'#fff6ce':e.type.body;ctx.fillRect(-e.r,-e.r*.65,e.r*2,e.r*1.3);ctx.fillStyle=e.type.top;ctx.fillRect(-e.r*.65,-e.r*.88,e.r*1.2,e.r*.4);ctx.fillStyle='#2d2028';ctx.fillRect(-e.r*.25,-e.r*.43,e.r*.17,e.r*.16);ctx.fillRect(e.r*.17,-e.r*.43,e.r*.17,e.r*.16);if(e.elite || e.boss){ctx.strokeStyle='#fff0a8';ctx.lineWidth=e.boss?4:2;ctx.strokeRect(-e.r-3,-e.r*.82,e.r*2+6,e.r*1.62);}if(e.boss){ctx.fillStyle='#ffe28a';ctx.font='bold 14px system-ui';ctx.fillText('BOSS',-18,-e.r-11);}ctx.restore();const w=e.boss?92:e.elite?46:30,barY=e.y-e.r-17;ctx.fillStyle='#172b2f';ctx.fillRect(e.x-w/2,barY,w,e.boss?8:5);ctx.fillStyle=e.boss?'#ffcb52':e.elite?'#ffd16d':e.type.top;ctx.fillRect(e.x-w/2,barY,w*Math.max(0,e.hp/e.maxHp),e.boss?8:5);ctx.fillStyle=e.boss?'#ffe28a':e.elite?'#f7e5aa':'#eefbf1';ctx.font=`bold ${e.boss?10:8}px system-ui`;ctx.textAlign='center';ctx.fillText(e.type.name,e.x,barY-15);ctx.fillStyle='#fff4bb';ctx.font='bold 8px system-ui';ctx.fillText(`DMG ${e.damage}`,e.x,barY-5);ctx.textAlign='left'; }
function drawLockedPads() { pads.forEach(pad=>{if(isPadUnlocked(pad)) return;ctx.globalAlpha=.82;hex(pad.x,pad.y,29,'#233f47','#72919a');ctx.globalAlpha=1;ctx.fillStyle='#d4e8dc';ctx.font='bold 8px system-ui';ctx.textAlign='center';ctx.fillText('LOCK',pad.x,pad.y+3);ctx.textAlign='left';}); }
function draw() { ctx.clearRect(0,0,W,H);ctx.fillStyle='#0d2930';ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(W/2,H/2);ctx.scale(camera.zoom,camera.zoom);ctx.translate(-camera.x,-camera.y);drawMap();drawLockedPads();drawPortal();for(const t of towers)drawPlacedTower(t);for(const e of enemies)drawEnemy(e);for(const s of shots){ctx.strokeStyle=s.color;ctx.lineWidth=s.kind==='spark'?3:5;ctx.beginPath();ctx.arc(s.x,s.y,s.kind==='spark'?3:5,0,Math.PI*2);ctx.stroke();}for(const p of particles){ctx.globalAlpha=Math.min(1,p.life*3);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.burst?(1-p.life)*38:p.size,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;}ctx.restore(); }
function loop(now) { const dt=Math.min(.035,(now-last)/1000);last=now;updateCamera(dt);if(!gameOver||running)update(dt);draw();requestAnimationFrame(loop); }
const restoredSave=loadGame();
loadPermanentProgress();
persistPermanentProgress();
if(restoredSave){ui.modalTitle.textContent='SAVE FOUND';ui.modalText.textContent='Your saved defense is ready to continue.';ui.startButton.textContent='CONTINUE DEFENSE';}
updateUI();requestAnimationFrame(loop);
